### ISSUE TITLE
gzipped log-file path validation

### ISSUE THREAD

**Issue by aylatalo** [Neo23x0/log4shell-detector#29]
The gzipped file path validation assumes that there is "log." string in path-name. This causes problems if log-file naming format is something like "SystemOut.log-20211212.gz". Could the dot (.) be removed from validation condition?

**Comment by Neo23x0** [comment]
Yes, I think that's possible

**Comment by Neo23x0** [comment]
Fixed in https://github.com/Neo23x0/log4shell-detector/commit/1deb5be776e4dc9e654fdf0ac0a2d665547f048a
