### ISSUE TITLE
Adapt README: Option --defaultpaths doesnt exist (I guess now called --auto?)

### ISSUE THREAD

**Issue by JoKeyser** [Neo23x0/log4shell-detector#32]
The README mentions the option `--defaultpaths`, but I guess this was renamed to `--auto`?

**Comment by Neo23x0** [comment]
Sorry, I had my booster shot yesterday and was out-of-service the whole afternoon due high fiver. (39.5 C)

I fixed it in https://github.com/Neo23x0/log4shell-detector/commit/ed16e50d0b7a1626a52701b4e8c241fda043af98
