### ISSUE TITLE
zip-compressed files support

### ISSUE THREAD

**Issue by aylatalo** [Neo23x0/log4shell-detector#37]
Please, evaluate and add attached code to support zip-compressed log-files as well.

[zip-support.zip](https://github.com/Neo23x0/log4shell-detector/files/7727578/zip-support.zip)
.

**Comment by Neo23x0** [comment]
Code as compressed attachment in an issue ... on Github?

**Comment by aylatalo** [comment]
Sorry, I'm kind a new to this. Trying to do it proper way.

**Comment by Neo23x0** [comment]
Ah, okay.

The right way to do it would be

1. Fork the repository. (there’s a button on the from page on the upper
right)
2. Use command line git or the Github Desktop client to clone that forked
repository to your local system. (
https://desktop.github.com/)
3. Commit and push the changes that you‘ve made to your forked repository
4. Create a pull request to my repository (this can also be done from the
main page of the repository by using „Compare“ or „Pull Request“)
-- 
Florian Roth

Key material (Keybase, S/MIME, PGP, Threema):
https://keybase.pub/johngalt/

**Comment by aylatalo** [comment]
Yes, done this. Thank you for your patience.
