### ISSUE TITLE
MemoryError - [E] Can't process FILE: xxxx REASON: None

### ISSUE THREAD

**Issue by boog1ebug** [Neo23x0/log4shell-detector#44]
scan_file
result = self.check_line(line)
File "xxxx/log4shell-detector-main/Log4ShellDetector/Log4ShellDetector.py", line 82, in check_line
linechars = list(decoded_line)
MemoryError
[E] Can't process FILE: xxxx REASON: None

This can be an issue, especially with --auto detection, unusual txt files and and memory limited environments. 

There is unnecessary list conversion in Log4ShellDetector. In this case no need to convert string to list in order to iterate the characters in the string. If list conversion is skipped, memory usage should decrease.

"for c in linechars:" is same as "for c in decoded_line:"

**Comment by Neo23x0** [comment]
fixed in https://github.com/Neo23x0/log4shell-detector/commit/3de1ed28d8bed380c82d8f53369fb92e7b5a5007
